### PR TITLE
NF: add --fast option to update

### LINKED ISSUE #24: add `--fast` option to `update`
Add the option to use `--fast` with `addurls` in the `update` command.

This is useful for updating the XNAT url for each of the files if it ever changes.

### PR DESCRIPTION
**Pull request by loj**
Closes #24

Pass the --fast option to addurls. The URLS will be added, but the content won't be downloaded.

### CODE REVIEW

**Comment by mih** [comment]
Log of online discussion: maybe we want to give `--fast` a different name to make clear that it would disable content verification. We can also think about turning it into a mode-type option like `datalad get --reckless`. Maybe even fuse it with the present `--force`.

**Comment by loj** [comment]
> We can also think about turning it into a mode-type option like `datalad get --reckless`.

I think this makes a lot of sense. I will put together something that adds `fast` as a mode under `--reckless`.

> Maybe even fuse it with the present `--force`.

I not sure that it works to combine these two, but I do think that `force` is not the right wording here. Perhaps we should consider renaming it to something like `reindex`.

**Comment by adswa** [comment]
> I not sure that it works to combine these two, but I do think that force is not the right wording here. Perhaps we should consider renaming it to something like reindex.

I like "reindex"

**Comment by mih** [comment]
I like reindex too. There is a similar issue with `init` https://github.com/datalad/datalad-xnat/issues/63

**Review by mih — APPROVED** [review]
LGTM, thx!

**Pull request merged**
